### ISSUE TITLE
How can we tackle re-authenticating when users change wallets? 

### ISSUE THREAD

**Issue by zkSoju** [ian/next-siwe#1]
`isAuthenticated` remains true even if users change wallets and the token stays the same, should this be intended?

**Comment by ian** [comment]
Good question. isAuthenticated is tied to the `token` from the server, not the wallet. So if they change wallets they are _still_ connected to the server using the original wallet.

A use case around this (for us specifically) is to authenticate using their hot wallet, but they can deploy a contract later using our platform with another wallet. We opted to let them stay connected with the other wallet but switch wallets for the transactions.

Do you think this is confusing? Or maybe we should make this a param that the implementer can control.

**Comment by ian** [comment]
FTR - `isAuthenticated` and `address` are both tied to the authentication, not the wallet connected. So a way to check for this would be:

```
import { useSIWE } from "next-siwe"
import { useAccount } from "wagmi"

const MyComponent = () => {
  const { address } = useAccount()
  const { address: authAddress } = useSIWE()

  const diffWallet = address != authAddress

  return (
    <div>
      Diff wallet? {JSON.stringify(diffWallet)}
    </div>
  )
}
```

**Comment by ian** [comment]
Proposed solution:

1. user controlled
```
const { address } = useAccount()
const { address: authAddress, logout } = useSIWE()

useEffect(() => {
  if(address != authAddress) {
    logout()
  }
}, [address, authAddress]
```

2. next-siwe controlled
```
<SiweProvider logoutOnWalletChange>
...
</SiweProvider>
```

**Comment by zkSoju** [comment]
> Good question. isAuthenticated is tied to the `token` from the server, not the wallet. So if they change wallets they are _still_ connected to the server using the original wallet.
> 
> A use case around this (for us specifically) is to authenticate using their hot wallet, but they can deploy a contract later using our platform with another wallet. We opted to let them stay connected with the other wallet but switch wallets for the transactions.
> 
> Do you think this is confusing? Or maybe we should make this a param that the implementer can control.

I think this makes the most sense considering Metamask keeps wallets connected, while SIWE can offer re-authentication on wallet switching.

**Comment by zkSoju** [comment]
> Good question. isAuthenticated is tied to the `token` from the server, not the wallet. So if they change wallets they are _still_ connected to the server using the original wallet.
> 
> A use case around this (for us specifically) is to authenticate using their hot wallet, but they can deploy a contract later using our platform with another wallet. We opted to let them stay connected with the other wallet but switch wallets for the transactions.
> 
> Do you think this is confusing? Or maybe we should make this a param that the implementer can control.



> Proposed solution:
> 
> 1. user controlled
> 
> ```
> const { address } = useAccount()
> const { address: authAddress, logout } = useSIWE()
> 
> useEffect(() => {
>   if(address != authAddress) {
>     logout()
>   }
> }, [address, authAddress]
> ```
> 
> 2. next-siwe controlled
> 
> ```
> <SiweProvider logoutOnWalletChange>
> ...
> </SiweProvider>
> ```

I had actually attempted the first solution without success being that I used login and I had issues with `signMessage` being undefined for some reason. The second solution is great though, can we add that in?

**Comment by ian** [comment]
Yup will add.

Should the default be to disconnect when wallet changes, or the default be stay logged in when wallet changes?

**Comment by zkSoju** [comment]
I think the default should be to logout when wallet changes, that seems to be common for dApps that integrate SIWE as well as my use case.

**Comment by ian** [comment]
Agreed. Will add it this week.

**Comment by zkSoju** [comment]
> Agreed. Will add it this week.

Thanks mate!

**Comment by zkSoju** [comment]
Do you happen to know why I might be receiving when deployed but not locally?
`Failed to load resource: the server responded with a status of 401 () api/siwe/me:1`

**Comment by ian** [comment]
@zkSoju any chance you can push a demo repo so I can see the error?

**Comment by zkSoju** [comment]
> @zkSoju any chance you can push a demo repo so I can see the error?

Sure! Here:

https://next-siwe-reprod.vercel.app/auth

https://github.com/zkSoju/next-siwe-reprod/

**Comment by ian** [comment]
@zkSoju added support for `staySignedInOnWalletChange` if you upgrade to 0.0.10.
